### ISSUE TITLE
5.8.1 all-min.jsf has an error in it

### ISSUE THREAD

**Issue by melloware** [webjars/font-awesome#47]
If you look at 5.8.1 all-min-jsf.css it has invalid URL in it.

If you look all-jsf.css works fine but all-min-jsf.css has a line 

```
src:url("#{resource['webjars:font-awesome/5.6.1/webfonts/fa-brands-400.eot);src:url(../webfonts/fa-brands-400.eot']}&#iefix"
```

The part "src:url(../webfonts/fa-brands-400.eot']}" is invalid because of the ".." and Mojarra is blowing up with the following error "Property resource[webjars:font-awesome/5.8.1/webfonts/fa-brands-400.eot);src:url(../webfonts/fa-brands-400.eot] contains more than one colon (:).":

```
2019-05-07 09:17:04,537 ERROR [io.undertow.request] (default task-15) UT005023: Exception handling request to /OASIS/javax.faces.resource/font-awesome/5.8.1/css/all.min-jsf.css.jsf: javax.el.ELException: Invalid resource format.  Property resource[webjars:font-awesome/5.8.1/webfonts/fa-brands-400.eot);src:url(../webfonts/fa-brands-400.eot] contains more than one colon (:).
                at com.sun.faces.application.resource.ResourceHelper$ELEvaluatingInputStream.evaluateExpressionIntoBuffer(ResourceHelper.java:793)
                at com.sun.faces.application.resource.ResourceHelper$ELEvaluatingInputStream.readExpressionIntoBufferAndEvaluateIntoBuffer(ResourceHelper.java:764)
                at com.sun.faces.application.resource.ResourceHelper$ELEvaluatingInputStream.read(ResourceHelper.java:728)
```

**Comment by melloware** [comment]
I assume it has to do with this line: https://github.com/webjars/font-awesome/blob/master/pom.xml#L141

**Comment by jamesward** [comment]
Hopefully @DennisRippinger can help us with this one.

**Comment by melloware** [comment]
OK PR submitted.  Used this regex tester to debug it:  https://regex101.com/r/uXORtm/4
